apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: tekton-github-trigger
spec:
  serviceAccountName: tekton-robot
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: build-deploy-bind
  template:
    ref: build-deploy-temp
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"