---
# tasks file for app_deployment_using_cephfs
# tasks file for app_deployment_using_cephfs
- name: create new project
  shell: oc new-project my-shared-storage

- name: deploy php application
  shell: oc new-app openshift/php:7.3-ubi7~https://github.com/christianh814/openshift-php-upload-demo --name=file-uploader

- name: wait for 5 mins
  wait_for:
    timeout: 300

- name: expose a service
  shell: oc expose svc/file-uploader -n my-shared-storage

- name: scale to 3 instances for high availability
  shell: oc scale --replicas=3 deployment/file-uploader -n my-shared-storage

- name: check the pods
  shell: oc get pods -n my-shared-storage

- name: create persistent volume claim and attach it to an application
  shell: oc set volume deployment/file-uploader --add --name=my-shared-storage -t pvc --claim-mode=ReadWriteMany --claim-size=1Gi --claim-name=my-shared-storage --claim-class=ocs-storagecluster-cephfs --mount-path=/opt/app-root/src/uploaded -n my-shared-storage

- name: check the pods
  shell: oc get pods -n my-shared-storage

- name: check the route that is created
  shell: oc get route file-uploader -n my-shared-storage -o jsonpath --template="{.spec.host}"
  register: app_route

- debug:
    msg: "{{ app_route.stdout }}"

- name: check if route is accessible or no
  command: curl -kv {{ app_route.stdout }}
  register: app_route_status

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://{{ app_route.stdout }}
  register: status

- debug:
    msg: "{{ status.status }}"
