---
# tasks file for create-ocs-cluster-service
- name: Login to the Openshift cli
  shell: oc login --token={{ ocp_login_token }} --server={{ ocp_api_url }}

- name: create temp directory for doing work in
  command: mktemp -d /tmp/ocs-service-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: create build config description for custom image
  template:
    src: create-ocs-service.yaml.j2
    dest: "{{ tempdir }}/create-ocs-service.yaml"

- name: deploy ocs operator
  shell: oc apply -f {{ tempdir }}/create-ocs-service.yaml

- name: wait for 8 mins
  wait_for:
    timeout: 480

- name: check storage class
  shell: oc get pods -n openshift-storage
  register: all_pods

- debug:
    msg: 
      - "{{ all_pods.stdout }}"
