---
- name: openshift container storage deployment
  hosts: localhost
  become: true
  roles:
    # - deploy-pipeline-operator
    # - configure-tekton
    - pipeline-tasks
    #- setup-pipeline-pipelinerun
    # - install-triggers-listeners
    # - trigger-pipeline-eventlistener
 
