---
- name: openshift pipeline tasks deployment
  hosts: localhost
  become: true
  roles:
    - deploy_pipeline_operator
    - configure_tekton
    - pipeline_tasks
    - setup_pipeline_pipelinerun
    - trigger_pipeline_eventlistener
 
