---
# tasks file for create-object-bucket-claim
- name: create temp directory for doing work in
  command: mktemp -d /tmp/obc-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: create build config description for custom image
  template:
    src: obc-claim.yaml.j2
    dest: "{{ tempdir }}/obc-claim.yaml"

- name: deploy ocs operator
  shell: oc apply -f {{ tempdir }}/obc-claim.yaml

# - name: check obc is created
#   shell: oc get obc -n openshift-storage
#   register: obc_name

# - debug:
#     msg: "{{ obc_name.stdout }}"

# - name: use OBC inside container
#   shell: curl -s https://github.com/red-hat-storage/ocs-training/blob/master/training/modules/ocs4/attachments/obc_app_example.yaml | oc apply -f 
- name: wait for 2 mins pod to be created
  wait_for:
    timeout: 120

- name: check pod
  shell: oc get pods -n obc-test -l app=obc-test
  register: pod_name

- name: check log of pod
  shell: kubectl logs -n obc-test -l app=obc-test
  register: pod_logs

- debug:
    msg: "{{ pod_logs }}"
